# Generated by Django 3.1.2 on 2020-12-07 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201206_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listings',
            field=models.ManyToManyField(to='auctions.Listing'),
        ),
        migrations.AddField(
            model_name='bid',
            name='number_of_bids',
            field=models.IntegerField(auto_created=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='listings',
            field=models.ManyToManyField(to='auctions.Listing'),
        ),
        migrations.AddField(
            model_name='comment',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='users',
            field=models.ManyToManyField(blank='True', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
