# Generated by Django 3.1.2 on 2020-12-08 02:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201207_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='listings',
            field=models.ManyToManyField(related_name='bids', to='auctions.Listing'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='users',
            field=models.ManyToManyField(related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='comment',
            name='listings',
            field=models.ManyToManyField(related_name='comments', to='auctions.Listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='users',
            field=models.ManyToManyField(related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='watchlisted',
            name='listings',
            field=models.ManyToManyField(related_name='watchlisted', to='auctions.Listing'),
        ),
        migrations.AlterField(
            model_name='watchlisted',
            name='users',
            field=models.ManyToManyField(related_name='watchlisted', to=settings.AUTH_USER_MODEL),
        ),
    ]
