# Generated by Django 3.1.2 on 2020-12-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='users',
        ),
        migrations.AddField(
            model_name='listing',
            name='categoryList',
            field=models.ManyToManyField(related_name='categoryList', to='auctions.Categories'),
        ),
    ]
