# Generated by Django 3.1.2 on 2020-12-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_watchlisted_trueorfalse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlisted',
            name='trueOrFalse',
            field=models.BooleanField(),
        ),
    ]
