# Generated by Django 3.1.2 on 2020-12-08 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201207_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlisted',
            old_name='trueOrFalse',
            new_name='yesOrNo',
        ),
    ]
